/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 0$
 * $Date: 0000-00-00$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		0
#define SVN_REVSTR	"0"
#define SVN_REVDATE	"0000-00-00"
#define SVN_REVSTAMP	00000000L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
