/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 35M$
 * $Date: 2012-06-24$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		35
#define SVN_REVSTR	"35M"
#define SVN_REVDATE	"2012-06-24"
#define SVN_REVSTAMP	20120624L
#define SVN_REVMODIFIED	2

#endif /* SVN_REV_H */
